repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/crate-ci/typos
    rev: v1.13.7
    hooks:
      - id: typos
        args: []
  - repo: https://github.com/yoheimuta/protolint
    rev: master
    hooks:
      - id: protolint
        args: [-fix, -config_path=.protolint.yaml]
